### PR TITLE
Fix nesting IMG tags within URL tags

### LINKED ISSUE #22: IMG BBCode within URL BBCode doesn't get parsed
As per [this post](https://www.phpbb.com/customise/db/extension/phpbb.de_external_images_as_link/support/topic/158696?p=584466#p584466) on phpBB.com

Apparently we mess too much with the new BBCode parser of 3.2.
As soon as this extension is installed, the IMG tag doesn't get parsed anymore when it's in a URL tag.

Lines that probably have to be changed and are the cause of this bug: https://github.com/phpbb-de/phpbb-ext-external-images-as-link/blob/33d8f2c656a123af58c0d62d5412a3d5d61ab15f/event/listener.php#L123-L126

Maybe, @JoshyPHP can help? :)

### PR DESCRIPTION
**Pull request by Elsensee**
Fixes #22.

### CODE REVIEW

**Comment by Crizz0** [comment]
Tested with PHP 5.6.12 and phpBB 3.1.11: works fine (so BC is good), 
PHP 5.6.31 and phpBB 3.2.1: works fine, PHP 7.0.23 and phpBB 3.2.1: works fine, too. 

In my "xampp" I have problems with: PHP 5.6.12 and phpBB 3.2.1: does not work. (hm?) After update to 5.6.31, the error stays the same. So maybe a config problem.

**Comment by Elsensee** [comment]
Not a configuration problem. (I debugged this for 3 hours now... DEDICATION! :D)

JoshyPHP said that depending on the version of TextFormatter that is bundled with phpBB I can use the method I in fact chose to use in this PR.
This can, however, only be used since version 0.11.0. (The version that will be included in phpBB 3.2.2)
phpBB 3.2.1 uses 0.10.0 and thus the fix I stated here won't do anything.

For phpBB 3.2.0 and 3.2.1 there are several ways to fix this - all ways are really ugly. I've chosen a not-so-ugly way and coded a quick fix (also in the last 3 hours - I've.. chosen some wrong ways before). You can find it here: https://gist.github.com/Elsensee/7e87a11b464194109a00d943d4a95b51

I'm not sure if we should include this in the extension. It is practically dead code after 3.2.2 and might come with unwanted side affects that I don't know of... So, you may decide. ;)

**Comment by Crizz0** [comment]
But I did check it with 3.2.1 and it worked.

**Comment by Elsensee** [comment]
Do you have the post that it worked with?

**Comment by Crizz0** [comment]
K, solved the false working stuff.

**Pull request merged**
